/**
 * Editorial seed content for the Community Forum: realistic South African discussion written for display-only personas
 * (community_personas, is_seed). Nobody here claims medical expertise, no product claims are made on SkinLabs' behalf, and every
 * thread is the kind of experience-sharing the guidelines ask for. `scripts/generate-community-seed.ts` turns this into SQL.
 *
 * BACKFILL: posts dated 15 Sep – 9 Oct 2026 (`d` = days after 15 Sep, `t` = SAST time).
 * POOL: posts released by the scheduled job after the migration (two a day, comments and likes trickling in over hours).
 */
export interface SeedComment { by: string; body: string; re?: number; likes?: number }
export interface SeedPost { by: string; cat: string; title: string; body: string; comments: SeedComment[]; likes: number; d?: number; t?: string }

export const PERSONAS: { name: string; role: "member" | "moderator" }[] = [
  "thando.glows", "naledi_in_jozi", "zinhle.k", "CapeTownCurls", "lerato_jhb", "kasi_glow", "dbn_dewy", "sipho.spf", "aisha_cpt", "pieter_dryskin",
  "mpho.m", "lindiwe.b", "karabo_skin", "nomsa.in.pta", "tumi_r", "bonolo.k", "ayanda_dbn", "refilwe_m", "jaco_vdm", "fatima.joburg",
  "zodwa.n", "lwazi_b", "megan_in_cpt", "busi.glow", "kopano_k", "anele.d", "themba.skincare", "nandi_m", "retha_pta", "siya.k",
].map((name) => ({ name, role: "member" as const }));

export const BACKFILL: SeedPost[] = [
  { by: "naledi_in_jozi", cat: "seasonal", d: 0, t: "07:42", likes: 14,
    title: "Spring has arrived and my face is peeling. Highveld friends, help?",
    body: "Joburg went from freezing to 29 degrees in a week and my cheeks are flaky while my forehead is oily. Winter routine feels too heavy now but I'm scared to change everything.\n\nWhat are you swapping first?",
    comments: [
      { by: "zinhle.k", body: "Same thing every September. I keep my gentle cleanser and just go to a lighter moisturiser, nothing else changes.", likes: 5 },
      { by: "Cole O.", re: 0, body: "Changing one thing at a time is a good instinct. Flaking plus oiliness is common when the weather swings. If it stings or gets worse, see your doctor.", likes: 4 },
      { by: "lerato_jhb", body: "Lekker thread. Also still wearing SPF every day, the UV is already savage here.", likes: 3 }] },
  { by: "CapeTownCurls", cat: "sun-care", d: 1, t: "09:15", likes: 11,
    title: "Wind + sunscreen at Clifton, how do you reapply without ruining your makeup?",
    body: "Beach days are starting and I never reapply because I'm either sandy or in a wetsuit. Stick? Spray? I just want something I'll actually use.",
    comments: [
      { by: "megan_in_cpt", body: "Stick for face, it lives in my beach bag. Spray goes everywhere in the wind, eish.", likes: 4 },
      { by: "pieter_dryskin", body: "Surfer here. Zinc-type stick on nose and cheeks, lotion on the rest, rinse and redo after every session. Ugly but it works.", likes: 5 },
      { by: "aisha_cpt", re: 1, body: "Do you find the zinc ones leave a white cast? I have deeper skin and that's my hold-up.", likes: 2 },
      { by: "pieter_dryskin", re: 2, body: "Some do, some are tinted. I'd test a few at Clicks before buying the big one.", likes: 2 }] },
  { by: "kasi_glow", cat: "acne", d: 1, t: "19:30", likes: 18,
    title: "Marks that stay long after the pimple is gone. Anyone else?",
    body: "I'm 24 and my acne has calmed but the dark marks on my cheeks are still there months later. People keep telling me to 'just use lemon' (I won't). What actually helped you?",
    comments: [
      { by: "Nicole N.", body: "Please skip the lemon, it can burn and darken skin. Daily sunscreen is what most people find matters most for marks fading. For anything stubborn, a dermatologist can help.", likes: 9 },
      { by: "thando.glows", body: "Patience and SPF. Mine took about 6 months to look better. Niacinamide helped me a bit but it's slow.", likes: 6 },
      { by: "busi.glow", body: "Same here sisi. The SPF is non negotiable, even on cloudy days.", likes: 3 }] },
  { by: "dbn_dewy", cat: "routines", d: 2, t: "06:55", likes: 9,
    title: "Durban humidity: is a 3-step routine enough?",
    body: "Cleanse, moisturise, sunscreen. That's it right now. I feel like everyone online has 10 steps. Is mine too basic for summer coming?",
    comments: [
      { by: "ayanda_dbn", body: "Three steps is plenty. In this humidity I even skip the moisturiser some mornings and just do SPF.", likes: 4 },
      { by: "Cole O.", body: "A simple routine you actually stick to beats a complicated one. Add something only when you have a specific reason.", likes: 6 },
      { by: "karabo_skin", body: "Agree. I did 8 steps for a year and my skin was worse. Back to 3 and no more drama.", likes: 3 }] },
  { by: "sipho.spf", cat: "budget-sa", d: 3, t: "12:20", likes: 16,
    title: "R200 sunscreens that don't feel like paint. Go.",
    body: "Varsity budget and I burn easily. I'm looking for a face sunscreen under R200 that isn't greasy and doesn't pill under my moisturiser. Dis-Chem or Clicks suggestions welcome.",
    comments: [
      { by: "zodwa.n", body: "Go for the lighter fluid or gel textures, the thick creams pill for me too. Check the price per ml, the big bottles are usually better value.", likes: 5 },
      { by: "lwazi_b", body: "Wait for the Clicks ClubCard promos, sunscreen goes on special quite often.", likes: 7 },
      { by: "Nicole N.", body: "Reminder that our reviews list the price, handy for comparing value. And whichever you choose, the one you'll wear daily is the right one.", likes: 4 }] },
  { by: "retha_pta", cat: "ingredients", d: 4, t: "20:05", likes: 7,
    title: "Is niacinamide at 10% too much? My cheeks are red",
    body: "Started a 10% niacinamide serum two weeks ago after seeing it everywhere. Now my cheeks are red and a bit tight. Do I stop, or is this my skin adjusting?",
    comments: [
      { by: "Cole O.", body: "Redness and tightness aren't something to push through. Pausing it and going back to basics for a week or two is reasonable. Lower strengths exist and many people do better on those.", likes: 8 },
      { by: "nomsa.in.pta", body: "I had the same with 10%. Switched to a 4% and it was fine. Pretoria dryness doesn't help either.", likes: 4 }] },
  { by: "fatima.joburg", cat: "deeper-skin-tones", d: 5, t: "08:10", likes: 21,
    title: "Sunscreen that doesn't leave a grey cast on deeper skin?",
    body: "I'm tired of looking like a ghost by 8am. Chemical filters feel lighter but some of them sting my eyes. Who here wears SPF daily on melanin-rich skin and what do you use?",
    comments: [
      { by: "thando.glows", body: "Chemical-filter gels or fluids are the least visible on me. For the eye sting, apply a bit further from the lash line.", likes: 8 },
      { by: "Nicole N.", body: "Great question and a common frustration. Tinted formulas can also blend better on deeper tones. Test along the jaw in daylight before committing.", likes: 6 },
      { by: "kasi_glow", re: 0, body: "Do you find the fluids ok in the Joburg heat? Mine seem to slide off by lunch.", likes: 2 },
      { by: "thando.glows", re: 2, body: "Blot first then reapply a thin layer. Not perfect but it works.", likes: 3 }] },
  { by: "pieter_dryskin", cat: "myths", d: 6, t: "17:45", likes: 12,
    title: "'You don't need sunscreen indoors or when it's cloudy' — true or false?",
    body: "My mate swears he's fine because he works in an office. I sit next to a big window and I'm not sure. What do you do?",
    comments: [
      { by: "Cole O.", body: "UVA passes through glass and cloud, so many people wear it daily regardless. If you sit by a bright window it's worth it.", likes: 7 },
      { by: "megan_in_cpt", body: "I put it on with my moisturiser every morning like brushing teeth. Can't be bothered to think about the weather.", likes: 3 }] },
  { by: "lindiwe.b", cat: "sensitive-skin", d: 7, t: "10:30", likes: 8,
    title: "Eczema-prone skin and load-shedding showers",
    body: "Eish, when the geyser is off I do quick cold-ish washes and my skin goes tight. When it's on I take long hot showers and it's worse. Any tips for gentle washing when the power is on and off?",
    comments: [
      { by: "zinhle.k", body: "Lukewarm, short, moisturiser on straight away while still damp. Worked for me more than any product.", likes: 6 },
      { by: "Nicole N.", body: "That's the usual advice, and it's worth mentioning it to your doctor if the eczema flares often, they can suggest what suits you.", likes: 4 },
      { by: "karabo_skin", body: "Fragrance-free body wash from the baby aisle at Clicks, nothing fancy.", likes: 3 }] },
  { by: "ayanda_dbn", cat: "acne", d: 8, t: "21:12", likes: 15,
    title: "Hormonal breakouts along the jaw every month. What's your plan?",
    body: "Same spot, same week, every month. I'm over trying a new cleanser each time. Gentle routine, no picking... or at least I'm trying. Has anything helped you? I'm seeing my GP next week but want to go prepared.",
    comments: [
      { by: "Cole O.", body: "Tracking when it flares (a simple note on your phone) gives your GP something concrete to work with. Good plan.", likes: 7 },
      { by: "busi.glow", body: "Mine was PCOS related, so the GP route was the right call for me. Skincare alone didn't cut it.", likes: 9 },
      { by: "mpho.m", body: "Keeping a gentle routine and not changing things every week stopped me making it worse.", likes: 4 }] },
  { by: "megan_in_cpt", cat: "ingredients", d: 9, t: "13:05", likes: 10,
    title: "Retinol starter guide? I'm 31 and scared of peeling",
    body: "I want to start but everyone has a horror story. How slowly did you go? Which nights? Moisturiser before or after?",
    comments: [
      { by: "Cole O.", body: "General approach: a low strength, a pea-sized amount, once or twice a week at night, and build up slowly. Avoid it during pregnancy and ask your doctor if you're unsure. SPF in the morning is a must.", likes: 11 },
      { by: "aisha_cpt", body: "I sandwich it: moisturiser, retinol, moisturiser. No peeling at all.", likes: 5 },
      { by: "jaco_vdm", body: "Twice a week for the first month. Boring, effective.", likes: 3 }] },
  { by: "tumi_r", cat: "budget-sa", d: 10, t: "07:25", likes: 13,
    title: "Takealot vs Dis-Chem vs Clicks. Where do you actually find the best skincare prices?",
    body: "I price-compare religiously now because the same moisturiser can differ by R40. Where are you buying and what's the trick?",
    comments: [
      { by: "lwazi_b", body: "ClubCard and Dis-Chem Benefit points add up. Takealot is good for bulk but check the seller.", likes: 6 },
      { by: "zodwa.n", body: "Always check the expiry on Takealot stuff from third-party sellers, I got burnt once.", likes: 8 },
      { by: "Nicole N.", body: "Good tip. Some of our review pages show current prices from SA retailers too, only when we've verified the listing.", likes: 5 }] },
  { by: "nomsa.in.pta", cat: "routines", d: 11, t: "18:40", likes: 9,
    title: "What does your Sunday night skin reset look like?",
    body: "I'm trying to build a small weekly habit. Mine is a gentle exfoliant once and a sheet mask while I watch something. What's yours, realistically?",
    comments: [
      { by: "thando.glows", body: "Honest answer: wash, moisturiser, bed. The sheet mask was costing me money and sleep.", likes: 5 },
      { by: "refilwe_m", body: "Clay mask on my T-zone only, 10 minutes, with a Rooibos. That's the whole thing.", likes: 6 }] },
  { by: "jaco_vdm", cat: "sun-care", d: 12, t: "11:15", likes: 6,
    title: "Braai-day sunburn on the tops of my ears again",
    body: "I do the face and neck properly and forget my ears and the back of my neck every single time. Anyone else, and how do you remember?",
    comments: [
      { by: "retha_pta", body: "I do ears first now. Silly rule but I no longer burn them.", likes: 4 },
      { by: "pieter_dryskin", body: "Hat with a brim and a sunscreen stick for ears. Ja nee.", likes: 3 },
      { by: "megan_in_cpt", body: "Also scalp if your hair is thin! Learnt that the hard way.", likes: 5 }] },
  { by: "zodwa.n", cat: "ask-the-community", d: 12, t: "20:00", likes: 8,
    title: "Gentle cleanser for oily skin that doesn't leave me squeaky?",
    body: "Every foaming cleanser makes my skin feel clean and then oilier an hour later. I'm in Soweto where it's dusty so I do need to wash properly. Suggestions?",
    comments: [
      { by: "kasi_glow", body: "Squeaky clean is the warning sign. Look for creamy or gel cleansers labelled gentle.", likes: 4 },
      { by: "Cole O.", body: "Once a day at night may be enough if you rinse with water in the morning, many people with oily skin find that kinder.", likes: 5 }] },
  { by: "busi.glow", cat: "deeper-skin-tones", d: 13, t: "09:50", likes: 17,
    title: "Hyperpigmentation around my mouth. Anyone else and what helped?",
    body: "It's been about a year and it's the one thing that makes me avoid selfies. I've tried a few creams but nothing consistent. I'm happy to see a derm but wondering what you tried first.",
    comments: [
      { by: "thando.glows", body: "A derm visit was the best money I spent. They looked at what was driving it before suggesting anything.", likes: 9 },
      { by: "Nicole N.", body: "Seeing a dermatologist is a sound next step, especially if it's persisted for a year. Sun protection daily in the meantime.", likes: 7 },
      { by: "fatima.joburg", body: "Same here. Also stopped picking at spots there, that made it worse.", likes: 4 }] },
  { by: "kopano_k", cat: "seasonal", d: 14, t: "15:30", likes: 7,
    title: "Hay fever season and my eyelids are itchy and puffy",
    body: "Every spring around Gauteng my eyelids go red and itchy. I try not to rub but it's hard. Anyone with the same thing and a gentle way to handle it?",
    comments: [
      { by: "Cole O.", body: "Seasonal allergies can affect eyelid skin. Worth asking a pharmacist or doctor what's safe near the eyes, rather than guessing with skincare.", likes: 6 },
      { by: "lerato_jhb", body: "Cold compress and not wearing eye makeup for a few days helps me feel better.", likes: 3 }] },
  { by: "karabo_skin", cat: "myths", d: 15, t: "19:20", likes: 14,
    title: "Toothpaste on pimples. Please tell me this is a myth",
    body: "My cousin swears by it. I tried it once as a teen and my skin was angry for a week. Just want to hear the community on this before I send her a voice note.",
    comments: [
      { by: "Nicole N.", body: "It's a myth that doesn't do skin any favours: toothpaste can irritate and burn. A simple routine and patience is kinder.", likes: 10 },
      { by: "ayanda_dbn", body: "Ha, my gran did the same. Send the voice note, with love.", likes: 6 },
      { by: "sipho.spf", body: "Gentle cleanser, don't pick, wait. Boring but true.", likes: 4 }] },
  { by: "aisha_cpt", cat: "routines", d: 16, t: "08:35", likes: 12,
    title: "Morning routine in under 5 minutes before the taxi",
    body: "I leave at 6:10 and honestly I don't have time. Mine: rinse, moisturiser, sunscreen, done. What's your fastest realistic routine?",
    comments: [
      { by: "zinhle.k", body: "Same. I keep sunscreen next to the kettle so I do it while it boils.", likes: 8 },
      { by: "tumi_r", body: "Habit stacking. Brush teeth, then face. Doesn't need willpower after a week.", likes: 5 }] },
  { by: "lwazi_b", cat: "ingredients", d: 17, t: "12:45", likes: 9,
    title: "Vitamin C serum turned orange. Is it still ok?",
    body: "I've had it for 4 months, it was pale yellow and now it's properly orange. Still tingles a little. Should I bin it?",
    comments: [
      { by: "Cole O.", body: "A colour change usually means the product has oxidised and may be less effective. Many people replace it. Keeping it away from heat and light helps next time.", likes: 7 },
      { by: "dbn_dewy", body: "Mine lives in the fridge in Durban summer. Orange means bin it for me.", likes: 4 }] },
  { by: "thando.glows", cat: "acne", d: 18, t: "20:40", likes: 19,
    title: "Stopped picking for 30 days. Results and what helped",
    body: "Not a miracle story, just a small win. I covered the mirror with a cloth, wore hydrocolloid patches on the worst ones and my skin has healed noticeably. Posting in case someone needs the push.",
    comments: [
      { by: "kasi_glow", body: "Proud of you sisi! This is the hardest part honestly.", likes: 9 },
      { by: "refilwe_m", body: "The cloth over the mirror trick is genius, stealing it.", likes: 6 },
      { by: "Cole O.", body: "Well done. Healing marks are slower than people expect, so this kind of habit change really counts.", likes: 7 }] },
  { by: "mpho.m", cat: "sun-care", d: 19, t: "07:50", likes: 10,
    title: "Is SPF 30 enough for a Joburg summer or should I go 50?",
    body: "I'm outside for the school run and then the office. Confusing labels, so many numbers. What are you using and why?",
    comments: [
      { by: "Cole O.", body: "Most people do well with a broad-spectrum SPF 30 to 50 used generously and reapplied. How much and how often you apply matters more than the number.", likes: 9 },
      { by: "sipho.spf", body: "Two finger lengths for face and neck was the rule that changed it for me.", likes: 7 }] },
  { by: "refilwe_m", cat: "ask-the-community", d: 20, t: "17:10", likes: 6,
    title: "Anyone tried the local rooibos / marula skincare brands?",
    body: "I keep seeing SA-made rooibos and marula oil products. Are they actually good or is it just nice packaging? Would love honest experiences.",
    comments: [
      { by: "zinhle.k", body: "Marula oil is nice as a last step on dry skin for me, but it's an oil so I skip it on humid days.", likes: 4 },
      { by: "Nicole N.", body: "We have a few SA brand reviews on the site if you want a second opinion. Always patch test botanical products first.", likes: 5 }] },
  { by: "anele.d", cat: "sensitive-skin", d: 21, t: "21:25", likes: 5,
    title: "Stinging when I apply anything after washing",
    body: "Even plain moisturiser stings for the first minute. It started after I over-exfoliated in August. How long did your barrier take to settle?",
    comments: [
      { by: "Cole O.", body: "Pausing all exfoliants and actives and using a very simple routine is the common approach. It can take a few weeks. If it isn't improving, see your doctor.", likes: 8 },
      { by: "lindiwe.b", body: "Took me about 6 weeks. Boring routine, no new products, and it settled.", likes: 6 }] },
  { by: "ayanda_dbn", cat: "budget-sa", d: 22, t: "10:05", likes: 11,
    title: "Hacks for stretching a moisturiser in a tight month",
    body: "End of the month and I'm down to the last bit of my moisturiser. Not buying another until payday. What do you do, other than watering it down (please don't)?",
    comments: [
      { by: "tumi_r", body: "Use it only on the dry spots and keep the rest of the face simple. Pea-sized amounts, it lasts longer.", likes: 5 },
      { by: "retha_pta", body: "Thin layer on damp skin spreads further. Not a trick, just physics.", likes: 6 }] },
  { by: "zinhle.k", cat: "routines", d: 23, t: "19:00", likes: 8,
    title: "Showing my skin diary after 3 months. What I'd change",
    body: "I logged every product and every flare for 3 months. The pattern was obvious: anything with fragrance and every time I skipped SPF. I'm simplifying everything. Anyone else keep a diary?",
    comments: [
      { by: "lindiwe.b", body: "Yes! It's how I found my own trigger. Notes app, nothing fancy.", likes: 5 },
      { by: "Nicole N.", body: "Great habit. It also gives your doctor or dermatologist something useful to look at.", likes: 7 }] },
  { by: "bonolo.k", cat: "myths", d: 24, t: "08:20", likes: 15,
    title: "Do pores actually 'open' and 'close' with hot and cold water?",
    body: "My aunt insists on a cold splash to close my pores. I thought pores don't have muscles? Settle it for us.",
    comments: [
      { by: "Cole O.", body: "Pores don't open and close like doors. Cold water can feel refreshing, but it won't change their size. Gentle cleansing is what helps keep them clear.", likes: 11 },
      { by: "naledi_in_jozi", body: "Sharing this with my aunt, thank you!", likes: 5 }] },
  { by: "siya.k", cat: "ask-the-community", d: 24, t: "16:15", likes: 4,
    title: "First time using a face mask. What should I start with?",
    body: "My girlfriend bought me one for my birthday and I have no idea. Dry cheeks, oily nose. Be gentle with me.",
    comments: [
      { by: "nandi_m", body: "Start gentle. Once a week, follow the time on the pack, and moisturiser afterwards. Happy birthday!", likes: 5 },
      { by: "Cole O.", body: "A simple hydrating mask is a good start. Patch test first, and rinse it off if it stings.", likes: 4 }] },
];

export const POOL: SeedPost[] = [
  { by: "naledi_in_jozi", cat: "sun-care", likes: 9, title: "UV index 11 in Joburg this week. What's your reapplication plan?",
    body: "The app says UV 11 by 10am. I'm in meetings all day but walk to lunch. Reapply once at lunch or is that not enough?",
    comments: [{ by: "sipho.spf", body: "I keep a stick at my desk and tap it over my face at lunch. Takes ten seconds." }, { by: "Cole O.", body: "Reapplying every two hours when you're outside is the usual guidance. Hats and shade help too." }, { by: "retha_pta", body: "Pretoria same story. Calendar reminder at 12:30 saved my cheeks." }] },
  { by: "dbn_dewy", cat: "seasonal", likes: 7, title: "Summer humidity and fungal acne scares. Anyone else?",
    body: "Little uniform bumps on my forehead every Durban summer. Doctor said it could be related to the heat and sweat. Light routine, no heavy oils for now. Anyone been through this?",
    comments: [{ by: "ayanda_dbn", body: "I get it on my chest too. Shower straight after the gym and change out of sweaty clothes helped." }, { by: "Cole O.", body: "Good that you've been to a doctor. Lighter products and not leaving sweat on the skin are common sense steps, and ask your doctor before trying anything new." }] },
  { by: "kasi_glow", cat: "deeper-skin-tones", likes: 16, title: "Shaving bumps on my jaw. Gentler options?",
    body: "I shave every morning for work and my jaw gets dark bumps. I've tried new razors, new foam. Any tips from guys and girls who've sorted this?",
    comments: [{ by: "kopano_k", body: "Shave after a warm shower, with the grain, and moisturise straight after. Changed my life." }, { by: "thando.glows", body: "Also changing the blade often. A blunt one is the worst." }, { by: "Nicole N.", body: "If it persists, a dermatologist can tell you what's going on and what's safe to use." }] },
  { by: "lerato_jhb", cat: "routines", likes: 11, title: "Night routine for someone who comes home at 9pm exhausted",
    body: "Load-shedding schedule, taxi, cooking. By the time I'm home I want to fall into bed. What's a two-minute night routine that still counts?",
    comments: [{ by: "aisha_cpt", body: "Micellar on a cotton pad, moisturiser. That's it, and my skin is fine." }, { by: "zinhle.k", body: "Keep your products where you can see them, not in the bathroom drawer. Out of sight = skipped." }] },
  { by: "pieter_dryskin", cat: "ingredients", likes: 8, title: "Ceramides, hyaluronic acid, glycerin: what's the difference in plain language?",
    body: "I keep seeing these on labels. Can someone explain without the jargon? I just want to know what to look for in a moisturiser for dry skin.",
    comments: [{ by: "Cole O.", body: "Simplified: humectants like glycerin and hyaluronic acid draw water in, ceramides help support the skin barrier, and occlusives like petrolatum seal it. Many moisturisers combine them." }, { by: "megan_in_cpt", body: "So that's why plain glycerin ones work for me. Thank you!" }] },
  { by: "tumi_r", cat: "budget-sa", likes: 12, title: "What's your 'repurchase forever' under R150?",
    body: "Not looking for hype, just that one thing you've bought five times because it works and doesn't cost a fortune.",
    comments: [{ by: "lwazi_b", body: "A basic fragrance-free moisturiser in a tub. I've lost count." }, { by: "zodwa.n", body: "Same. Boring wins." }, { by: "fatima.joburg", body: "Plain petroleum jelly for lips and dry patches. Cheap and it works." }] },
  { by: "mpho.m", cat: "acne", likes: 13, title: "How long before I should expect results from a new acne product?",
    body: "I'm 3 weeks into a new routine and my skin looks the same. Stay the course or switch?",
    comments: [{ by: "Cole O.", body: "Skin cycles take weeks, and many routines need 6 to 12 weeks before you can judge. Too much switching can make things worse." }, { by: "busi.glow", body: "Took me 10 weeks to see a real difference. Hang in there." }] },
  { by: "refilwe_m", cat: "myths", likes: 10, title: "'Natural' means safer for sensitive skin. Is it?",
    body: "My granny only uses things 'from the garden'. I read that natural oils can cause reactions too. Where do you land?",
    comments: [{ by: "Nicole N.", body: "Natural doesn't automatically mean gentle. Plant extracts and essential oils are common allergens, and patch testing is wise for anything new." }, { by: "karabo_skin", body: "Learnt that with a tea tree oil disaster." }] },
  { by: "fatima.joburg", cat: "sensitive-skin", likes: 9, title: "Mask-wearing at work and irritation along my nose",
    body: "Back in a clinic setting and my nose bridge is red and dry from my mask. Any ideas that don't involve skipping the mask?",
    comments: [{ by: "lindiwe.b", body: "A thin layer of plain moisturiser underneath before the shift. Changed my face." }, { by: "Cole O.", body: "Gentle cleansing after shifts and a simple barrier moisturiser is the usual starting point. If it breaks or weeps, check with your doctor." }] },
  { by: "nandi_m", cat: "ask-the-community", likes: 6, title: "Skincare gift ideas for my mom (dry, mature skin, 58)",
    body: "Her birthday is coming and I'd like to gift something she'll actually use. Not too many steps and not fancy. Ideas?",
    comments: [{ by: "retha_pta", body: "A really good moisturiser and a daily sunscreen she likes the feel of. Practical and thoughtful." }, { by: "ayanda_dbn", body: "Add a nice lip balm and hand cream, those always get used." }] },
  { by: "sipho.spf", cat: "sun-care", likes: 14, title: "Got a mole checked at a pharmacy clinic. Here's what it was like",
    body: "I got a mole looked at and it was quick, friendly and I was told to see a dermatologist for follow-up. Just sharing so the idea feels less scary if you're putting yours off.",
    comments: [{ by: "Cole O.", body: "Thank you for sharing. Any new, changing or unusual mole is worth having checked. Early checks are always better." }, { by: "pieter_dryskin", body: "Booking mine this week because of this post." }, { by: "megan_in_cpt", body: "Do it! I did last year, all clear, huge relief." }] },
  { by: "thando.glows", cat: "routines", likes: 10, title: "When did you realise you were over-doing it?",
    body: "I had 11 products, then my skin freaked out. Now it's 4 and honestly it looks better. What was your wake-up call?",
    comments: [{ by: "zinhle.k", body: "Stinging at everything. Went back to cleanser, moisturiser, SPF." }, { by: "aisha_cpt", body: "Five different actives at once. Never again." }] },
  { by: "ayanda_dbn", cat: "seasonal", likes: 8, title: "Chafing and heat rash while commuting in summer",
    body: "Taxi rides in 35 degrees and I'm sweating. Heat rash on my neck every time. Lightweight clothing helps but any skin tips?",
    comments: [{ by: "dbn_dewy", body: "Talc-free powder and loose cotton. And a cool shower when I get home." }, { by: "Cole O.", body: "Keeping skin cool and dry helps. If a rash is painful or doesn't settle, see a doctor." }] },
  { by: "jaco_vdm", cat: "ingredients", likes: 7, title: "Is zinc oxide the same as 'mineral sunscreen'?",
    body: "I see 'mineral', 'physical' and 'zinc' used like they're all the same. Are they?",
    comments: [{ by: "Cole O.", body: "Roughly yes: mineral or physical sunscreens use filters like zinc oxide or titanium dioxide that sit on the skin, instead of chemical filters." }, { by: "megan_in_cpt", body: "Zinc ones were the only ones that didn't make my eyes sting." }] },
  { by: "karabo_skin", cat: "acne", likes: 12, title: "Mask-ne from gym headbands and caps",
    body: "Breakouts along my hairline and forehead. I wash my cap rarely, to be honest. Any other culprits?",
    comments: [{ by: "kasi_glow", body: "Hair products too. My pomade was the problem." }, { by: "Nicole N.", body: "Washing caps and headbands regularly and showering after training is a simple place to start." }] },
  { by: "retha_pta", cat: "budget-sa", likes: 9, title: "Are expensive serums worth it or is it the sunscreen that matters?",
    body: "I've spent a lot on serums and I'm starting to think my sunscreen is doing the heavy lifting. Opinions?",
    comments: [{ by: "sipho.spf", body: "Sunscreen first, always. Everything else is a bonus." }, { by: "Cole O.", body: "For most people, daily sunscreen, a gentle cleanser and a moisturiser cover the essentials. Serums are optional and worth buying only for a specific goal." }] },
  { by: "lwazi_b", cat: "deeper-skin-tones", likes: 15, title: "Keloid-prone skin and piercing. Advice please",
    body: "I want another ear piercing but I've had a keloid before. Has anyone been through this and what did your doctor say?",
    comments: [{ by: "busi.glow", body: "My doctor told me to avoid piercing altogether. Worth asking before you do anything." }, { by: "Nicole N.", body: "Speaking to a doctor or dermatologist first is the right call if you've had a keloid." }] },
  { by: "zodwa.n", cat: "routines", likes: 7, title: "Sunday skin-care playlist, what's yours?",
    body: "Slow-down day. I put on some amapiano, do my 10 minute routine. What do you listen to?",
    comments: [{ by: "kasi_glow", body: "Amapiano soft hours! Habit loop for me." }, { by: "thando.glows", body: "Mine's Yvonne Chaka Chaka and tea. Whatever works." }] },
  { by: "megan_in_cpt", cat: "sun-care", likes: 8, title: "Does SPF in makeup count?",
    body: "My foundation says SPF 30. Can I skip sunscreen under it?",
    comments: [{ by: "Cole O.", body: "Most people don't apply enough foundation to reach the stated SPF, so a separate sunscreen underneath is the safer approach." }, { by: "aisha_cpt", body: "Sunscreen first, foundation after. Didn't realise." }] },
  { by: "naledi_in_jozi", cat: "ask-the-community", likes: 5, title: "Best way to remove stubborn sunscreen without scrubbing?",
    body: "Water-resistant sunscreen clings. A single cleanse doesn't always get it all off. Tips?",
    comments: [{ by: "pieter_dryskin", body: "Oil cleanser or balm first, then a gentle wash. Melts it right off." }, { by: "retha_pta", body: "Micellar water also works for me before cleansing." }] },
  { by: "dbn_dewy", cat: "myths", likes: 11, title: "Is 'detox' skincare a thing?",
    body: "Charcoal this, detox that. Does skin actually need to be detoxed?",
    comments: [{ by: "Nicole N.", body: "Your liver and kidneys do the detoxing. 'Detox' on a label is a marketing term. A gentle clean is enough." }, { by: "zinhle.k", body: "Saved me a lot of money, thank you." }] },
  { by: "kopano_k", cat: "sensitive-skin", likes: 6, title: "New washing powder and my arms are itching",
    body: "I changed laundry brand last week and my skin is itchy and bumpy. Could it be that?",
    comments: [{ by: "Cole O.", body: "Changing laundry products can trigger irritation in some people. Switching back, rinsing twice and asking a pharmacist or doctor if it persists is sensible." }, { by: "lindiwe.b", body: "Fragrance-free washing powder fixed it for me." }] },
  { by: "tumi_r", cat: "routines", likes: 9, title: "Double cleansing in a house with a shared bathroom: realistic?",
    body: "I share with two flatmates and bathroom time is gold. Can I do a quick routine and still get the benefit?",
    comments: [{ by: "ayanda_dbn", body: "Cleanse in the shower, moisturiser at your desk. Works." }, { by: "mpho.m", body: "I keep a small basket in my room and use the bathroom just for rinsing." }] },
  { by: "busi.glow", cat: "acne", likes: 10, title: "Which fabrics are kindest to acne-prone skin on pillow nights?",
    body: "Do pillowcases really matter? Changing weekly or more often?",
    comments: [{ by: "kasi_glow", body: "Weekly for me, and a clean towel for the face." }, { by: "Cole O.", body: "Fresh pillowcases weekly is a reasonable habit. It's one small thing, not a cure." }] },
  { by: "pieter_dryskin", cat: "seasonal", likes: 6, title: "Cold front incoming: lip balm and hands survival kit",
    body: "Cape Town cold snap this week. My lips and knuckles are first to crack. What's in your kit?",
    comments: [{ by: "megan_in_cpt", body: "Thick hand cream at night with cotton gloves, lip balm everywhere." }, { by: "aisha_cpt", body: "Plain petroleum jelly. Done." }] },
  { by: "fatima.joburg", cat: "ingredients", likes: 12, title: "Azelaic acid for redness: has anyone tried it?",
    body: "Saw it mentioned as gentle for redness and marks. Are you using it and how did your skin react?",
    comments: [{ by: "thando.glows", body: "Mild tingling at first, then fine. I use it a few nights a week." }, { by: "Cole O.", body: "People often tolerate it well, but patch test, start slowly, and check with your doctor if you're pregnant or have a skin condition." }] },
  { by: "siya.k", cat: "budget-sa", likes: 7, title: "Is it okay to use body moisturiser on my face?",
    body: "I ran out of face moisturiser and my sister says her body lotion is fine. Is it?",
    comments: [{ by: "Cole O.", body: "Body lotions often contain fragrance and heavier ingredients that don't suit some faces. For a day or two it's fine for many people, but a face moisturiser is generally the better choice." }, { by: "nandi_m", body: "Fragrance gave me a rash, so I won't." }] },
  { by: "lindiwe.b", cat: "routines", likes: 8, title: "Pregnant and rewriting my skincare. What's your experience?",
    body: "Just found out I'm expecting and I'm confused about what to stop. I'll check with my doctor but would love to hear how others simplified.",
    comments: [{ by: "Nicole N.", body: "Congratulations! Your doctor or midwife is the best person to advise on which ingredients to avoid. Many people simplify to cleanser, moisturiser and sunscreen." }, { by: "lerato_jhb", body: "I stopped all my actives and asked at my check-up. Easiest route." }] },
  { by: "anele.d", cat: "sun-care", likes: 5, title: "Sunscreen and school kids. Any recommendations?",
    body: "My 8 year old refuses sunscreen because it stings his eyes. Anything that works for kids?",
    comments: [{ by: "ayanda_dbn", body: "Stick versions went down well with mine. Also a hat." }, { by: "Cole O.", body: "A paediatrician or pharmacist can recommend a child-friendly formula, and shade and clothing help too." }] },
  { by: "karabo_skin", cat: "ask-the-community", likes: 6, title: "Dermatologist waiting times in Joburg. Tips for getting seen?",
    body: "I called three rooms and the earliest was in 6 weeks. Anyone know a quicker route?",
    comments: [{ by: "fatima.joburg", body: "Ask to be on a cancellations list. Mine called me within two weeks." }, { by: "Nicole N.", body: "A GP referral sometimes helps, and our Consult directory is coming soon to make this easier." }] },
  { by: "zinhle.k", cat: "myths", likes: 9, title: "Does drinking more water clear your skin?",
    body: "Everyone says 3 litres a day. I'm drinking loads and my skin looks the same. Thoughts?",
    comments: [{ by: "Cole O.", body: "Staying hydrated is good for you, but water alone isn't a skin treatment. Skin concerns usually need more than that." }, { by: "pieter_dryskin", body: "Moisturiser did more than water for me." }] },
  { by: "thando.glows", cat: "deeper-skin-tones", likes: 13, title: "Dark circles that run in the family",
    body: "Everyone in my family has them. Is anything actually helping or is it just genes?",
    comments: [{ by: "busi.glow", body: "Sleep and SPF around the eyes helped me a bit, but mine are genetic too." }, { by: "Nicole N.", body: "Genetics play a big role. A gentle eye-area routine and sun protection are sensible, and a doctor can check anything unusual." }] },
  { by: "kasi_glow", cat: "routines", likes: 11, title: "Starting a skin journal. What do you track?",
    body: "Thinking of doing the diary thing. What should I write down so it's useful and not a chore?",
    comments: [{ by: "zinhle.k", body: "Date, new products, sleep, period, stress, and a quick photo in the same light weekly." }, { by: "Cole O.", body: "Keep it short enough that you'll stick to it. Consistency matters more than detail." }] },
];
