import { Helmet } from "react-helmet-async";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AIFormulator from "@/components/AIFormulator";

const AIFormulatorPage = () => {
  return (
    <>
      <Helmet>
        <title>AI Formulator — Free Personalized Skincare Routine | SKINLABS</title>
        <meta
          name="description"
          content="Get a dermatologist-grade, personalized skincare routine generated by AI from your unique skin profile — free to try, no account required. Delivered as a downloadable PDF report."
        />
        <link rel="canonical" href="https://skinlabs.co.za/ai-formulator" />
        <meta property="og:title" content="AI Formulator — Free Personalized Skincare Routine | SKINLABS" />
        <meta
          property="og:description"
          content="A free AI-powered skincare formulator that builds your AM/PM routine, actives schedule and product recommendations from your skin profile."
        />
        <meta property="og:url" content="https://skinlabs.co.za/ai-formulator" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="https://skinlabs.co.za/pwa-512.png" />
        <script type="application/ld+json">{JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebApplication",
          "name": "SKINLABS AI Skincare Formulator",
          "applicationCategory": "HealthApplication",
          "operatingSystem": "Web",
          "url": "https://skinlabs.co.za/ai-formulator",
          "description": "Personalized AI-generated skincare routines grounded in dermatology literature, with downloadable PDF reports. Free to try, no account required.",
          "offers": { "@type": "Offer", "price": "0", "priceCurrency": "ZAR" }
        })}</script>
      </Helmet>

      <div className="min-h-screen bg-background">
        <Header />
        <main className="pt-20">
          <AIFormulator />
        </main>
        <Footer />
      </div>
    </>
  );
};

export default AIFormulatorPage;
