/**
 * Generates supabase/migrations/20261009130000_community_seed_content.sql from scripts/community-seed/content.ts.
 * Deterministic: likes are drawn with a seeded PRNG, so re-running produces the same file. Run: bun run scripts/generate-community-seed.ts
 */
import { writeFileSync } from "node:fs";
import { BACKFILL, PERSONAS, POOL, type SeedPost } from "./community-seed/content";

const names = PERSONAS.map((p) => p.name);
const hash = (s: string) => [...s].reduce((h, c) => (Math.imul(h, 31) + c.charCodeAt(0)) | 0, 7);
const rng = (seed: number) => () => {
  seed = (seed + 0x6d2b79f5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
const pick = (n: number, exclude: string[], seed: string): string[] => {
  const r = rng(hash(seed));
  const pool = names.filter((x) => !exclude.includes(x));
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(r() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, Math.min(n, pool.length));
};

const expand = (p: SeedPost) => ({
  by: p.by,
  cat: p.cat,
  title: p.title,
  body: p.body,
  likes: pick(p.likes, [p.by], `post:${p.title}`),
  comments: p.comments.map((c, i) => ({
    by: c.by,
    body: c.body,
    ...(c.re !== undefined ? { re: c.re } : {}),
    likes: pick(c.likes ?? Math.max(1, 1 + ((hash(p.title + i) >>> 0) % 4)), [c.by], `c:${p.title}:${i}`),
  })),
});

const sast = (d: number, t: string) => {
  const day = new Date(Date.UTC(2026, 8, 15 + d));
  return `${day.toISOString().slice(0, 10)}T${t}:00+02:00`;
};
for (const p of [...BACKFILL, ...POOL]) {
  for (const c of p.comments) if (c.body.length > 1500) throw new Error(`comment too long in ${p.title}`);
  if (p.body.trim().length < 10 || p.title.length > 140) throw new Error(`bad post ${p.title}`);
}

const backfill = BACKFILL.map((p) => ({ at: sast(p.d ?? 0, p.t ?? "09:00"), ...expand(p) }));
const pool = POOL.map(expand);
const j = (v: unknown) => JSON.stringify(v, null, 0);

const sql = `-- Community Forum seed content, generated by scripts/generate-community-seed.ts from scripts/community-seed/content.ts. Do not hand-edit.
--  * ${PERSONAS.length} display-only personas with South African handles (is_seed = true: no login, no email, never notified, removable).
--  * ${BACKFILL.length} discussions dated 15 Sep - 9 Oct 2026 with threaded comments and likes (all in the past, none after now()).
--  * ${POOL.length} more discussions queued for the \`community-seed-tick\` job (two a day, 08:05 and 18:25 SAST, comments/likes over the following hours).
-- Remove everything: delete the community_posts rows whose persona_id is a seed persona (comments and likes cascade), then the personas.
-- Idempotent: skipped when the first persona already exists.

DO $seed$
DECLARE v_post jsonb;
BEGIN
  IF EXISTS (SELECT 1 FROM public.community_personas WHERE display_name = ${`'${names[0]}'`}) THEN RETURN; END IF;

  INSERT INTO public.community_personas (display_name, role) VALUES
${names.map((n) => `    ('${n}', 'member')`).join(",\n")}
  ON CONFLICT (display_name) DO NOTHING;

  FOR v_post IN SELECT * FROM jsonb_array_elements($json$${j(backfill)}$json$::jsonb) LOOP
    PERFORM public.community_seed_add_post(v_post, (v_post ->> 'at')::timestamptz, false);
  END LOOP;

  INSERT INTO public.community_seed_queue (due_at, payload)
  SELECT ((((now() AT TIME ZONE 'Africa/Johannesburg')::date + 1 + ((o - 1) / 2))::timestamp
           + CASE WHEN (o - 1) % 2 = 0 THEN time '08:05' ELSE time '18:25' END
           + (abs(hashtext(e ->> 'title')) % 40) * interval '1 minute') AT TIME ZONE 'Africa/Johannesburg'), e
    FROM jsonb_array_elements($json$${j(pool)}$json$::jsonb) WITH ORDINALITY AS t(e, o);
END
$seed$;
`;
writeFileSync("supabase/migrations/20261009130000_community_seed_content.sql", sql);
console.log(`personas ${names.length}, backfill ${backfill.length}, pool ${pool.length}, bytes ${sql.length}`);
