/**
 * Seeds review_price_targets for the STATIC review catalogue (src/data/reviews.ts), which the edge
 * functions can't read at runtime. Generated reviews get their targets from a database trigger.
 * Re-run after adding static reviews and apply the emitted migration (idempotent: ON CONFLICT DO NOTHING).
 *   bun run scripts/generate-review-price-targets.ts > supabase/migrations/<ts>_review_price_targets_static_seed.sql
 */
import { productReviews } from "../src/data/reviews.ts";
import { parseSizeMl } from "../supabase/functions/_shared/pricing/match.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const rows = productReviews.map((r) => {
  const size = parseSizeMl(r.product_name);
  return `  (${q(r.id)}, 'static', ${q(r.product_name)}, ${q(r.brand || "Unknown")}, ${size ?? "NULL"}, ${r.where_to_buy?.toLowerCase().includes("sponsor") ? "true" : "false"})`;
});
console.log(`-- Static catalogue review price targets (generated by scripts/generate-review-price-targets.ts; ${rows.length} reviews).
INSERT INTO public.review_price_targets (review_id, review_kind, product_name, brand, size_ml, is_sponsored) VALUES
${rows.join(",\n")}
ON CONFLICT (review_id) DO NOTHING;`);
