// Emits SQL that (re)fills public.weekly_featured_brands for the next N ISO
// weeks, used by enqueue_weekly_top_brands_email(). Each week features one
// product category (rotating) and its top 3 brands by average SkinLabs review
// score (efficacy, value, texture, SA climate fit), from the NON-sponsored
// editorial catalogue only. Re-run when the catalogue changes or the table runs
// out of weeks:
//   bun run scripts/generate-weekly-featured-brands.ts [weeks] [startDate] > supabase/migrations/<ts>_weekly_featured_brands_refresh.sql
import { productReviews, overallScore } from "../src/data/reviews";

const THEMES: Array<{ category: string; label: string }> = [
  { category: "Serum", label: "serum" },
  { category: "Moisturiser", label: "moisturiser" },
  { category: "Cleanser", label: "cleanser" },
  { category: "Sunscreen", label: "sunscreen" },
  { category: "Body", label: "body care" },
];

const weeks = Number(process.argv[2] ?? 20);
const start = new Date((process.argv[3] ?? new Date().toISOString().slice(0, 10)) + "T00:00:00Z");

/** Monday of the ISO week containing d (UTC). */
const monday = (d: Date) => {
  const x = new Date(d);
  x.setUTCDate(x.getUTCDate() - ((x.getUTCDay() + 6) % 7));
  return x;
};
const isoWeekLabel = (d: Date) => {
  const t = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
  t.setUTCDate(t.getUTCDate() + 4 - (t.getUTCDay() || 7));
  const yearStart = new Date(Date.UTC(t.getUTCFullYear(), 0, 1));
  const week = Math.ceil(((t.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
  return `${t.getUTCFullYear()}-W${String(week).padStart(2, "0")}`;
};
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const top3 = (category: string) => {
  const byBrand = new Map<string, typeof productReviews>();
  for (const r of productReviews.filter((r) => !r.is_sponsored && r.category === category)) {
    byBrand.set(r.brand, [...(byBrand.get(r.brand) ?? []), r]);
  }
  return [...byBrand.entries()]
    .map(([brand, rs]) => {
      const sorted = [...rs].sort((a, b) => overallScore(b) - overallScore(a));
      return {
        brand,
        avg: rs.reduce((a, r) => a + overallScore(r), 0) / rs.length,
        n: rs.length,
        top: sorted[0],
      };
    })
    .sort((a, b) => b.avg - a.avg || b.n - a.n || a.brand.localeCompare(b.brand))
    .slice(0, 3);
};

const rows: string[] = [];
for (let i = 0; i < weeks; i++) {
  const d = new Date(monday(start).getTime() + i * 7 * 86400000);
  const theme = THEMES[i % THEMES.length];
  top3(theme.category).forEach((b, rank) => {
    rows.push(
      `  (${q(isoWeekLabel(d))}, ${q(theme.label)}, ${rank + 1}, ${q(b.brand)}, ${b.avg.toFixed(1)}, ${b.n}, ${q(b.top.product_name)}, ${q(b.top.id)})`,
    );
  });
}
console.log(`-- Generated by scripts/generate-weekly-featured-brands.ts (${weeks} weeks from ${start.toISOString().slice(0, 10)}).
INSERT INTO public.weekly_featured_brands (week_label, theme, rank, brand, avg_score, review_count, top_product, top_product_id) VALUES
${rows.join(",\n")}
ON CONFLICT (week_label, rank) DO UPDATE SET theme = EXCLUDED.theme, brand = EXCLUDED.brand, avg_score = EXCLUDED.avg_score,
  review_count = EXCLUDED.review_count, top_product = EXCLUDED.top_product, top_product_id = EXCLUDED.top_product_id;`);
