-- First 10 product reviews for the new review pipeline (see api/product-review-sync.ts
-- and CLAUDE.md's "Product review pipeline" entry), hand-seeded by Claude during
-- pipeline setup rather than generated by the live Gemini pipeline (generated_by =
-- 'claude-manual-seed', ids prefixed aigen- to match the pipeline's own id scheme).
-- Every product is real: 4 sourced from already-verified OpenHaus marketplace_products
-- rows, 2 from Faithful to Nature (verified via Firecrawl's search index after FTN's
-- live site returned a Cloudflare 403 to this environment -- see CLAUDE.md's
-- infrastructure notes), 1 from Geve Skincare's own site, and 3 disclosed-sponsored
-- reviews of real Timeless Skincare products (USD prices converted at an approximate
-- ~18.5 ZAR/USD rate). 7 South African / 3 global-available-in-SA -- the 70/30 split
-- the product brief asked for.
INSERT INTO public.ai_generated_product_reviews
  (id, product_name, brand, local_price_zar, where_to_buy, category, skin_type_match,
   score_efficacy, score_value, score_texture, score_climate, verdict, key_ingredients,
   retailers, origin, source_url, source_type, is_sponsored, generated_by, data_quality_status, published_date)
VALUES
('aigen-esse-bakuchiol-serum', 'Bakuchiol Serum', 'Esse', 597.99, 'OpenHaus Marketplace', 'Serum',
 ARRAY['Dry','Sensitive','Mature'], 7.5, 6.5, 8.5, 8.0,
 'A gentle plant-based retinol alternative -- bakuchiol is genuinely evidence-backed for smoothing texture and fading pigmentation without retinol''s irritation risk, and Esse backs the formula with real PETA cruelty-free certification rather than just a label claim.',
 ARRAY['Bakuchiol','Aloe Vera','Jojoba Seed Oil'],
 '[]'::jsonb, 'south_africa', 'https://skinlabs.co.za/marketplace/product/esse-bakuchiol-serum', 'openhaus_marketplace', false, 'claude-manual-seed', 'unverified', CURRENT_DATE),

('aigen-lelive-good-to-glow-body-exfoliator', 'Good to Glow Smooth + Renew Body Exfoliator', 'Lelive', 210.99, 'OpenHaus Marketplace', 'Exfoliant',
 ARRAY['Normal','Oily','Combination'], 7.5, 8.5, 8.0, 7.5,
 'A hybrid chemical-and-physical body scrub that is smart about not over-relying on manual abrasion -- the AHA/PHA pairing does the real exfoliating work while the jojoba beads just help distribute it evenly. Genuinely useful for rough, congested body skin at a fair price.',
 ARRAY['AHA','PHA','Jojoba Beads','Green Rooibos'],
 '[]'::jsonb, 'south_africa', 'https://skinlabs.co.za/marketplace/product/lelive-good-to-glow-smooth-renew-body-exfoliator', 'openhaus_marketplace', false, 'claude-manual-seed', 'unverified', CURRENT_DATE),

('aigen-skoon-skin-pjs-face-mist', 'Skin PJs Face Mist - Hydrating Toner with Buchu & CBD', 'SKOON.', 362.99, 'OpenHaus Marketplace', 'Mist',
 ARRAY['Sensitive','Dry'], 6.0, 6.5, 8.0, 8.0,
 'A pleasant hydrating mist rather than a treatment -- buchu and CBD are calming, not clinically potent actives here, so this earns its place as a barrier-priming layer before serum rather than a stand-alone fix for sensitivity.',
 ARRAY['Buchu','CBD'],
 '[]'::jsonb, 'south_africa', 'https://skinlabs.co.za/marketplace/product/skoon-skin-pjs-face-mist-buchu-cbd', 'openhaus_marketplace', false, 'claude-manual-seed', 'unverified', CURRENT_DATE),

('aigen-standard-beauty-5-lactic-acid-toner', '5% Lactic Acid Toner', 'Standard Beauty', 140.99, 'OpenHaus Marketplace', 'Exfoliant',
 ARRAY['Normal','Combination','Mature'], 7.0, 9.0, 7.5, 7.5,
 'A gentle-strength lactic acid at a real, disclosed concentration -- mild enough for two-to-three-times-a-week use without the irritation risk of a glycolic exfoliant, and priced like Standard Beauty''s other actives: genuinely affordable.',
 ARRAY['Lactic Acid'],
 '[]'::jsonb, 'south_africa', 'https://skinlabs.co.za/marketplace/product/standard-beauty-5-lactic-acid-toner', 'openhaus_marketplace', false, 'claude-manual-seed', 'unverified', CURRENT_DATE),

('aigen-hey-gorgeous-vitamin-c-boosting-serum', 'Vitamin C Boosting Serum', 'Hey Gorgeous', 529.00, 'Faithful to Nature', 'Serum',
 ARRAY['Normal','Combination'], 7.5, 6.5, 7.5, 7.0,
 'A straightforward L-ascorbic acid vitamin C serum -- the real, well-evidenced form of vitamin C, not a stabilised derivative dressed up as equivalent. Squalane softens the delivery, but there is no ferulic acid or vitamin E here to extend stability and photoprotection the way the best-in-class vitamin C serums do, and L-ascorbic acid degrades faster in SA heat and sun exposure, so storage matters.',
 ARRAY['L-Ascorbic Acid','Magnesium Ascorbyl Phosphate','Squalane'],
 jsonb_build_array(jsonb_build_object('retailer','Faithful to Nature','price_zar',529.00,'in_stock',true,'url','https://www.faithful-to-nature.co.za/hey-gorgeous-vitamin-c-boosting-serum')),
 'south_africa', 'https://www.faithful-to-nature.co.za/hey-gorgeous-vitamin-c-boosting-serum', 'faithful_to_nature', false, 'claude-manual-seed', 'unverified', CURRENT_DATE),

('aigen-eco-diva-superfood-face-serum', 'Superfood Face Serum', 'Eco Diva', 525.00, 'Faithful to Nature', 'Serum',
 ARRAY['Dry','Normal'], 7.0, 7.0, 8.0, 8.5,
 'A genuinely well-built oil blend leaning on real African botanicals -- baobab and marula alongside jojoba, argan, sesame and apricot kernel oils -- more of a nourishing facial oil than a targeted vitamin C treatment despite the branding. The citrus and tea tree oils in the blend mean fragrance-sensitive skin should patch test first.',
 ARRAY['Baobab Seed Oil','Marula Seed Oil','Argan Oil','Jojoba Seed Oil','Hyaluronic Acid'],
 jsonb_build_array(jsonb_build_object('retailer','Faithful to Nature','price_zar',525.00,'in_stock',true,'url','https://www.faithful-to-nature.co.za/eco-diva-natural-superfood-face-serum')),
 'south_africa', 'https://www.faithful-to-nature.co.za/eco-diva-natural-superfood-face-serum', 'faithful_to_nature', false, 'claude-manual-seed', 'unverified', CURRENT_DATE),

('aigen-geve-skin-refining-earthmoss-serum', 'Skin Refining Earthmoss Serum', 'Geve', 950.00, 'Brand Direct', 'Serum',
 ARRAY['Dry','Normal'], 7.0, 5.5, 7.5, 7.0,
 'Geve''s clinical-adjacent positioning is backed by real retailer listings describing measurable hydration improvement, though we could not independently verify the brand''s own percentage claims or see a full ingredient deck on the listings we checked. At R950 for 30ml, it is priced like a premium clinic-brand serum -- worth it only if the undisclosed formula matches that price for you.',
 ARRAY['Earthmoss Extract'],
 jsonb_build_array(jsonb_build_object('retailer','Brand Direct','price_zar',950.00,'in_stock',true,'url','https://geveskincare.com/products/moss-serum')),
 'south_africa', 'https://geveskincare.com/products/moss-serum', 'brand_direct', false, 'claude-manual-seed', 'unverified', CURRENT_DATE),

('aigen-timeless-vitamin-c-e-ferulic-acid-serum', '20% Vitamin C + E Ferulic Acid Serum', 'Timeless Skin Care', 517.00, 'Brand Direct', 'Serum',
 ARRAY['Normal','Combination','Mature'], 9.0, 8.5, 7.0, 6.5,
 'The vitamin C + E + ferulic acid combination is one of the best-evidenced antioxidant stacks in skincare, and Timeless''s 20% version hits all three actives at a price that undercuts most SA-available equivalents even after import shipping. As with any high-strength L-ascorbic acid serum, storage away from heat and light matters more in SA''s climate than the brand''s own packaging suggests. This review discloses a sponsored placement with Timeless Skincare.',
 ARRAY['Vitamin C (L-Ascorbic Acid) 20%','Vitamin E','Ferulic Acid'],
 jsonb_build_array(jsonb_build_object('retailer','Brand Direct','price_zar',517.00,'in_stock',true,'url','https://www.timelessha.com/products/20-vitamin-c-e-ferulic-acid-serum-1-oz')),
 'global_available_in_sa', 'https://www.timelessha.com/products/20-vitamin-c-e-ferulic-acid-serum-1-oz', 'sponsored', true, 'claude-manual-seed', 'unverified', CURRENT_DATE),

('aigen-timeless-matrixyl-synthe-6-serum', 'Matrixyl Synthe''6 Peptides Serum', 'Timeless Skin Care', 536.00, 'Brand Direct', 'Serum',
 ARRAY['Mature','Normal'], 7.5, 8.0, 7.5, 8.0,
 'Matrixyl Synthe''6 at a disclosed 2% concentration is a genuinely well-studied peptide complex for collagen support. Timeless''s single-active approach means you are not paying for filler, but you will want a separate vitamin C or exfoliating step since this serum does one job only. This review discloses a sponsored placement with Timeless Skincare.',
 ARRAY['Matrixyl Synthe''6 (Peptide Complex)'],
 jsonb_build_array(jsonb_build_object('retailer','Brand Direct','price_zar',536.00,'in_stock',true,'url','https://www.timelessha.com/products/matrixyl-synthe6-serum-1-oz')),
 'global_available_in_sa', 'https://www.timelessha.com/products/matrixyl-synthe6-serum-1-oz', 'sponsored', true, 'claude-manual-seed', 'unverified', CURRENT_DATE),

('aigen-timeless-hyaluronic-acid-100-pure', 'Hyaluronic Acid 100% Pure Serum', 'Timeless Skin Care', 240.00, 'Brand Direct', 'Serum',
 ARRAY['Dry','Normal','Combination'], 6.5, 9.0, 8.0, 8.5,
 'A no-frills hyaluronic acid serum at one of the lowest per-ml prices we have seen for a single-active HA product, SA import cost included. Multi-molecular-weight claims are not disclosed, so layer it under a proper moisturiser rather than expecting it to seal in hydration on its own -- genuinely useful in SA''s dry inland climate either way. This review discloses a sponsored placement with Timeless Skincare.',
 ARRAY['Hyaluronic Acid'],
 jsonb_build_array(jsonb_build_object('retailer','Brand Direct','price_zar',240.00,'in_stock',true,'url','https://www.timelessha.com/products/hyaluronic-acid-serum-100-pure')),
 'global_available_in_sa', 'https://www.timelessha.com/products/hyaluronic-acid-serum-100-pure', 'sponsored', true, 'claude-manual-seed', 'unverified', CURRENT_DATE)
ON CONFLICT (id) DO NOTHING;
