-- Ingredients Intelligence content-population, Track B batch 01: 12 new real
-- ingredients created from supabase/INGREDIENT_EXPANSION_CANDIDATES.md's
-- Humectant/Exfoliant-AHA/Exfoliant-Enzyme/Antioxidant/Brightening/Soothing-Botanical
-- sections, each with genuine PubMed research (never fabricated). See
-- supabase/INGREDIENT_CONTENT_STATUS.md for the full batch log and live counts.
-- Identity + full content created in one INSERT per ingredient (not a separate
-- identity-then-enrich pass, since research was already done for each).

INSERT INTO public.ingredients (slug, inci_name, common_name, category, description, function_summary, typical_concentration_range, evidence_level, verification_status, source_url, source_type, source_date, confidence, last_verified_at)
VALUES
  ('betaine', 'Betaine', NULL, 'humectant',
   'A naturally occurring osmolyte (trimethylglycine) found in beets and other plants, used in skincare as a humectant and cell-protectant.',
   'Organic osmolyte studied for protecting skin cells from oxidative and UV-induced stress -- in vitro research shows it (alongside related osmolytes like taurine) helps preserve tight-junction barrier function in UVB-irradiated keratinocytes and is taken up by dermal fibroblasts as a protective response to osmotic/UV stress. Direct human efficacy trials specific to betaine as a standalone humectant are lacking.',
   NULL, 'limited', 'partially_verified', 'https://doi.org/10.1038/s41598-018-22533-0', 'peer_reviewed_literature', '2018-03-26', 'low'::confidence_level, now()),

  ('sodium-pca', 'Sodium PCA', NULL, 'humectant',
   'The sodium salt of pyrrolidone carboxylic acid (PCA), a genuine component of skin''s natural moisturizing factor (NMF).',
   'A natural moisturizing factor (NMF) component -- human stratum corneum studies show PCA, alongside lactate/urea/sodium/potassium, is reduced in dry/anhidrotic skin and in atopic dermatitis, correlating with lower hydration. These studies establish PCA''s physiological role in NMF by measuring endogenous levels, rather than testing topical sodium PCA supplementation directly.',
   NULL, 'limited', 'partially_verified', 'https://doi.org/10.1016/j.jdermsci.2013.06.005', 'peer_reviewed_literature', '2013-06-25', 'low'::confidence_level, now()),

  ('trehalose', 'Trehalose', NULL, 'humectant',
   'A naturally occurring disaccharide known for stabilizing cell membranes and proteins under stress conditions, used in skincare as a humectant/stress-protectant.',
   'Humectant and stress-protectant sugar -- included among skin-barrier-improving co-ingredients recommended to offset retinoid irritation in a formulation review, and a component of a multi-ingredient rosacea cream (with cholesterol/ceramide/fatty acids) shown in an open-label clinical study to reduce erythema and improve barrier measures. Evidence for trehalose''s own standalone contribution is not isolated from these ingredient blends.',
   NULL, 'limited', 'partially_verified', 'https://doi.org/10.2147/CCID.S69410', 'peer_reviewed_literature', '2014-10-24', 'low'::confidence_level, now()),

  ('urea', 'Urea', NULL, 'humectant',
   'A natural moisturizing factor component and mild keratolytic agent, one of the most extensively studied moisturizing actives in dermatology.',
   'Humectant and mild keratolytic -- a randomized, controlled, single-blind right-vs-left trial in ichthyosis vulgaris patients found a 10% urea lotion produced a significantly greater reduction in scaling, roughness, redness and cracking than a standard glycerol-based emollient cream over 4 weeks, with comparable tolerability.',
   '10% (studied concentration in the head-to-head RCT); also formulated at higher keratolytic-strength concentrations', 'moderate', 'partially_verified', 'https://doi.org/10.1185/03007995.2011.628381', 'peer_reviewed_literature', '2011-10-19', 'medium'::confidence_level, now()),

  ('malic-acid', 'Malic Acid', NULL, 'exfoliant-aha',
   'A fruit-derived alpha hydroxy acid (AHA), often used alongside other AHAs like glycolic and lactic acid.',
   'Alpha hydroxy acid explored primarily as a permeation enhancer and peptide-delivery vehicle component in recent transdermal-delivery research, and identified as a bioactive AHA extractable from plant sources. Direct clinical efficacy data on malic acid as a standalone exfoliant is limited compared with glycolic/lactic acid.',
   NULL, 'limited', 'partially_verified', 'https://doi.org/10.1039/d5tb00580a', 'peer_reviewed_literature', '2025-07-30', 'low'::confidence_level, now()),

  ('citric-acid', 'Citric Acid', NULL, 'exfoliant-aha',
   'A fruit-derived alpha hydroxy acid commonly used both as a pH-adjusting ingredient and, at higher concentrations, a chemical-peel exfoliant.',
   'AHA and pH-adjuster -- used at high concentrations in professional chemical peels for exfoliation. A documented emergency-medicine case report describes significant chemical burns and airway compromise following a professionally applied high-concentration citric acid facial peel, underscoring that concentration and professional application matter significantly for this ingredient''s safety profile.',
   NULL, 'limited', 'partially_verified', 'https://doi.org/10.1016/s0736-4679(02)00435-3', 'peer_reviewed_literature', '2002-05-01', 'low'::confidence_level, now()),

  ('gluconolactone', 'Gluconolactone', NULL, 'exfoliant-aha',
   'A polyhydroxy acid (PHA) exfoliant known for a gentler profile than classic AHAs, also functioning as a humectant and antioxidant.',
   'Polyhydroxy acid exfoliant -- two real split-face clinical studies found 10% and 30% gluconolactone chemical peels significantly improved skin hydration while lowering pH, sebum and transepidermal water loss (TEWL), with no significant difference between the two concentrations, supporting its use as a gentler exfoliant that also strengthens barrier measures.',
   '10-30% (studied range in split-face clinical trials)', 'moderate', 'partially_verified', 'https://doi.org/10.1111/jocd.15864', 'peer_reviewed_literature', '2023-06-19', 'medium'::confidence_level, now()),

  ('papain', 'Papain', NULL, 'exfoliant-enzyme',
   'A proteolytic (protein-digesting) enzyme derived from papaya, used in skincare for enzymatic exfoliation.',
   'Enzymatic exfoliant -- a systematic literature review found real in vitro/in vivo evidence that papain and related proteolytic enzymes can exfoliate skin and improve select skin characteristics, though only a small number of clinical studies exist. A separate mechanistic study found papain degrades keratinocyte tight-junction proteins and can act as a skin sensitizer/allergen independent of its enzymatic activity -- an important safety consideration for formulators and a reason to patch-test enzyme exfoliants.',
   NULL, 'moderate', 'partially_verified', 'https://doi.org/10.1111/jocd.14673', 'peer_reviewed_literature', '2021-12-12', 'medium'::confidence_level, now()),

  ('resveratrol', 'Resveratrol', NULL, 'antioxidant',
   'A polyphenol antioxidant (stilbene) found in grapes, berries and Japanese knotweed, widely used in anti-aging skincare formulations.',
   'Antioxidant active, typically formulated alongside other antioxidants -- a 12-week clinical study of a nighttime serum containing 1% resveratrol, baicalin and vitamin E found statistically significant improvements in fine lines/wrinkles, firmness, elasticity, hyperpigmentation and dermal thickness in photodamaged skin; a separate clinical study combining resveratrol with green tea polyphenols and caffeine reduced facial redness in all 16 subjects by 6 weeks. Both trials tested resveratrol as part of a multi-antioxidant blend rather than in isolation.',
   '1% (studied concentration in the photoaging serum trial)', 'moderate', 'partially_verified', 'https://pubmed.ncbi.nlm.nih.gov/25607790/', 'peer_reviewed_literature', '2014-12-01', 'medium'::confidence_level, now()),

  ('alpha-lipoic-acid', 'Thioctic Acid', 'Alpha Lipoic Acid', 'antioxidant',
   'A naturally occurring, both water- and fat-soluble antioxidant, marketed in skincare as alpha lipoic acid (ALA) or thioctic acid.',
   'Dual water/fat-soluble antioxidant -- a randomized, double-blind, placebo-controlled split-face trial (33 women, 12 weeks) found a 5% alpha lipoic acid cream significantly improved measures of facial photoaging, including a 50.8% reduction in skin roughness by laser profilometry versus 40.7% for the placebo-treated side of the face.',
   '5% (studied concentration in the split-face RCT)', 'moderate', 'partially_verified', 'https://doi.org/10.1046/j.1365-2133.2003.05597.x', 'peer_reviewed_literature', '2003-10-01', 'medium'::confidence_level, now()),

  ('azelaic-acid', 'Azelaic Acid', NULL, 'brightening',
   'A naturally occurring dicarboxylic acid with dual anti-inflammatory and brightening/tyrosinase-inhibiting properties, widely used for acne, rosacea and hyperpigmentation.',
   'A systematic review and meta-analysis of 21 randomized controlled trials for rosacea found azelaic acid to be an effective, well-tolerated topical treatment with a better efficacy profile than metronidazole (though less effective than ivermectin). Azelaic acid is also well established in the acne/hyperpigmentation literature for its dual anti-inflammatory and tyrosinase-inhibiting brightening action.',
   NULL, 'strong', 'partially_verified', 'https://doi.org/10.1016/j.ad.2024.12.026', 'peer_reviewed_literature', '2025-04-15', 'high'::confidence_level, now()),

  ('allantoin', 'Allantoin', NULL, 'soothing-botanical',
   'A soothing, skin-conditioning compound found naturally in comfrey (Symphytum officinale) root and other plants, with a long history of cosmetic use.',
   'Soothing/skin-conditioning active -- a rat wound-healing study using comfrey-root-extract creams (allantoin identified as a key regenerative compound alongside rosmarinic acid) found faster, more complete wound healing versus controls. A human pilot study of a multi-ingredient eczema moisturizer containing allantoin and bisabolol found significant improvements in irritation, erythema, itching and hydration after 2 weeks, though allantoin''s individual contribution wasn''t isolated from the other actives in that formulation.',
   NULL, 'moderate', 'partially_verified', 'https://doi.org/10.3390/ijms25063099', 'peer_reviewed_literature', '2024-03-07', 'medium'::confidence_level, now());

-- Multi-source citations (2 per ingredient)
INSERT INTO public.ingredient_sources (ingredient_id, source_url, source_title, publisher, source_type, publication_date, evidence_level, evidence_summary)
SELECT i.id, v.source_url, v.source_title, v.publisher, 'peer_reviewed_literature'::data_source_type, v.publication_date::date, v.evidence_level::evidence_level, v.evidence_summary
FROM (VALUES
  ('betaine', 'https://doi.org/10.1038/s41598-018-22533-0', 'Organic osmolytes preserve the function of the developing tight junction in ultraviolet B-irradiated rat epidermal keratinocytes', 'Scientific Reports', '2018-03-26', 'limited', 'In vitro study: organic osmolytes (incl. betaine) preserved tight-junction barrier function in UVB-irradiated keratinocytes by protecting claudin-1/claudin-4 localization.'),
  ('betaine', 'https://doi.org/10.1111/j.1600-0625.2008.00746.x', 'Ultraviolet A induces transport of compatible organic osmolytes in human dermal fibroblasts', 'Experimental Dermatology', '2008-06-14', 'limited', 'Human dermal fibroblasts accumulate betaine/taurine/myo-inositol as a cell-protective response to hyperosmotic and UVA stress; taurine specifically inhibited UVA-induced IL-6.'),
  ('sodium-pca', 'https://doi.org/10.1016/j.jdermsci.2013.06.005', 'Sweat constitutes several natural moisturizing factors, lactate, urea, sodium, and potassium', 'Journal of Dermatological Science', '2013-06-25', 'limited', 'Anhidrotic (non-sweating) skin areas showed significantly lower PCA/lactate/urea/sodium/potassium and lower stratum corneum hydration than adjacent hidrotic areas.'),
  ('sodium-pca', 'https://doi.org/10.1016/j.jdermsci.2012.02.011', 'Decreased lactate and potassium levels in natural moisturizing factor from the stratum corneum of mild atopic dermatitis patients', 'Journal of Dermatological Science', '2012-03-01', 'limited', 'PCA, lactate, urea, sodium and potassium were significantly decreased in NMF from mild atopic dermatitis skin versus healthy controls.'),
  ('trehalose', 'https://doi.org/10.1155/2024/5551774', 'A Comprehensive Review of the Strategies to Reduce Retinoid-Induced Skin Irritation in Topical Formulation', 'Dermatology Research and Practice', '2024-08-17', 'limited', 'Review names trehalose (with glucosamine, ectoine, sucralfate) among ingredients combined with retinoids to improve skin barrier and hydration and reduce irritation.'),
  ('trehalose', 'https://doi.org/10.2147/CCID.S69410', 'Preliminary open-label clinical evaluation of the soothing and reepithelialization properties of a novel topical formulation for rosacea', 'Clinical, Cosmetic and Investigational Dermatology', '2014-10-24', 'limited', 'Trehalose-containing rosacea cream (with cholesterol/ceramide/fatty acids) significantly reduced erythema index and transepidermal water loss versus untreated skin.'),
  ('urea', 'https://doi.org/10.1185/03007995.2011.628381', 'Efficacy of topical 10% urea-based lotion in patients with ichthyosis vulgaris', 'Current Medical Research and Opinion', '2011-10-19', 'moderate', '30-patient, right-vs-left RCT: 10% urea lotion produced significantly greater reduction in scaling/roughness/redness/cracking than glycerol-based emollient (65% vs 40% relative reduction, p=0.0001).'),
  ('malic-acid', 'https://doi.org/10.1039/d5tb00580a', 'Dual-function supramolecular system of alpha-hydroxy acid-based ionic liquids and peptides for enhanced anti-aging transdermal delivery', 'Journal of Materials Chemistry B', '2025-07-30', 'limited', 'Malic-acid-derived ionic liquid combined with a peptide improved transdermal peptide permeation 3.10-fold and clinically reduced wrinkles over 28 days in a small trial.'),
  ('malic-acid', 'https://doi.org/10.3390/molecules28093963', 'Extraction of Isoflavones, Alpha-Hydroxy Acids, and Allantoin from Soybean Leaves', 'Molecules', '2023-05-08', 'limited', 'Analytical extraction-optimization study confirming malic acid and citric acid as real, extractable bioactive AHA compounds alongside allantoin.'),
  ('citric-acid', 'https://doi.org/10.1016/s0736-4679(02)00435-3', 'Airway compromise after routine alpha-hydroxy facial peel administration', 'The Journal of Emergency Medicine', '2002-05-01', 'limited', 'Case report of secondary burns to the neck/face and airway compromise following a professionally applied high-concentration citric acid facial peel.'),
  ('gluconolactone', 'https://doi.org/10.1111/srt.13353', 'Split-face evaluation: Gluconolactone plus oxybrasion versus gluconolactone plus microneedling', 'Skin Research and Technology', '2023-06-01', 'moderate', '21-subject split-face study: 10% gluconolactone peel combined with either oxybrasion or microneedling increased hydration and decreased sebum/pH/TEWL, with no significant difference between methods.'),
  ('gluconolactone', 'https://doi.org/10.1111/jocd.15864', 'Evaluation of the effects of 10% and 30% gluconolactone chemical peel on sebum, pH, and TEWL', 'Journal of Cosmetic Dermatology', '2023-06-19', 'moderate', '16-subject split-face study: both 10% and 30% gluconolactone peels significantly reduced skin pH and TEWL and showed seboregulatory effects, with no significant difference between concentrations.'),
  ('papain', 'https://doi.org/10.1111/jocd.14673', 'An overview of the use of proteolytic enzymes as exfoliating agents', 'Journal of Cosmetic Dermatology', '2021-12-12', 'moderate', 'Systematic literature review of 11 studies: papain, bromelain and other proteolytic enzymes can exfoliate skin and improve select skin characteristics; few clinical (vs. in vitro) studies exist.'),
  ('papain', 'https://doi.org/10.1038/jid.2015.58', 'Papain Degrades Tight Junction Proteins of Human Keratinocytes In Vitro and Sensitizes C57BL/6 Mice via the Skin', 'Journal of Investigative Dermatology', '2015-02-23', 'moderate', 'Papain degraded tight-junction proteins in human keratinocytes and acted as a potent epicutaneous allergen/sensitizer in mice, independent of its enzymatic activity.'),
  ('resveratrol', 'https://pubmed.ncbi.nlm.nih.gov/25607790/', 'Evaluation of efficacy and tolerance of a nighttime topical antioxidant containing resveratrol, baicalin, and vitamin E for treatment of mild to moderately photodamaged skin', 'Journal of Drugs in Dermatology', '2014-12-01', 'moderate', '12-week clinical study: 1% resveratrol/0.5% baicalin/1% vitamin E serum significantly improved wrinkles, firmness, elasticity, hyperpigmentation and dermal thickness (18.9% by ultrasound) in photodamaged skin.'),
  ('resveratrol', 'https://pubmed.ncbi.nlm.nih.gov/23884488/', 'Reduction of facial redness with resveratrol added to topical product containing green tea polyphenols and caffeine', 'Journal of Drugs in Dermatology', '2013-07-01', 'moderate', '16-subject clinical study: resveratrol/green tea polyphenol/caffeine combination reduced facial redness in all 16 subjects by clinical photo assessment within 6-12 weeks, no adverse effects observed.'),
  ('alpha-lipoic-acid', 'https://doi.org/10.1046/j.1365-2133.2003.05597.x', 'Randomized, placebo-controlled, double blind study on the clinical efficacy of a cream containing 5% alpha-lipoic acid related to photoageing of facial skin', 'British Journal of Dermatology', '2003-10-01', 'moderate', '33-subject, 12-week, split-face RCT: 5% alpha lipoic acid cream significantly reduced skin roughness (50.8% vs 40.7% for placebo, p<0.001) by laser profilometry.'),
  ('alpha-lipoic-acid', 'https://doi.org/10.1046/j.1467-2494.2002.00159.x', 'Role of topical and nutritional supplement to modify the oxidative stress', 'International Journal of Cosmetic Science', '2002-12-01', 'limited', 'RCT of topical/oral antioxidant blend incl. alpha-lipoic acid: reduced oxidative stress and lipid peroxidation markers by 30-40% in blood serum of treated subjects.'),
  ('azelaic-acid', 'https://doi.org/10.1016/j.ad.2024.12.026', 'Efficacy of Widely Used Topical Drugs for Rosacea: A Systematic Review and Meta-Analysis', 'Actas Dermo-Sifiliograficas', '2025-04-15', 'strong', 'Systematic review and meta-analysis of 21 RCTs: azelaic acid is effective and well-tolerated for rosacea, with a better efficacy profile than metronidazole (though less effective than ivermectin).'),
  ('azelaic-acid', 'https://doi.org/10.1007/s40265-024-02003-w', 'Microencapsulated Benzoyl Peroxide for Rosacea in Context: A Review of the Current Treatment Landscape', 'Drugs', '2024-02-29', 'strong', 'Review of FDA-approved rosacea treatments confirms azelaic acid gel/foam as an established, effective option for reducing papulopustular lesions and erythema.'),
  ('allantoin', 'https://doi.org/10.3390/ijms25063099', 'Healing of Skin Wounds in Rats Using Creams Based on Symphytum Officinale Extract', 'International Journal of Molecular Sciences', '2024-03-07', 'moderate', 'Comfrey-root-extract cream (allantoin + rosmarinic acid identified as key bioactives) produced faster, more complete skin-wound healing in rats versus controls over 14 days.'),
  ('allantoin', 'https://doi.org/10.1111/jocd.12199', 'A pilot study investigating the efficacy of botanical anti-inflammatory agents in an OTC eczema therapy', 'Journal of Cosmetic Dermatology', '2015-11-24', 'moderate', '25-subject pilot study: multi-ingredient moisturizer containing allantoin and bisabolol significantly improved eczema irritation, erythema, itching (79% reduction) and hydration (44% increase) after 2 weeks.')
) AS v(candidate_slug, source_url, source_title, publisher, publication_date, evidence_level, evidence_summary)
JOIN public.ingredients i ON i.slug = v.candidate_slug
ON CONFLICT (ingredient_id, source_url) DO NOTHING;
