-- Manual Analysis Pass issuing (Admin dashboard > Analysis Passes tab).
--
-- An admin can issue Analysis Passes to a member identified by email address, with
-- no payment. Passes are what unlock the Advanced AI Dermatology Analysis
-- (get_advanced_assessment_access), so this reuses the existing ledger
-- (ai_credit_transactions / available_ai_credits) and changes nothing about how a
-- pass is spent or refunded.
--
-- Audit: its own table rather than admin_audit_log, whose `action` CHECK only allows
-- role/entitlement actions. (Widening a CHECK needs DROP CONSTRAINT, which the
-- Supabase SQL tool can't run.) Append-only: no INSERT/UPDATE/DELETE grant to any
-- client role; rows are written only by admin_issue_analysis_passes().
--
-- No DROP statements anywhere in this file, on purpose (see CLAUDE.md, Supabase MCP gotcha).

CREATE TABLE IF NOT EXISTS public.analysis_pass_grants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  admin_user_id uuid NOT NULL,
  target_user_id uuid NOT NULL,
  target_email text NOT NULL,
  credits int NOT NULL CHECK (credits BETWEEN 1 AND 25),
  note text NOT NULL CHECK (char_length(btrim(note)) BETWEEN 1 AND 200),
  transaction_id uuid,
  request_id uuid UNIQUE
);
CREATE INDEX IF NOT EXISTS idx_analysis_pass_grants_created ON public.analysis_pass_grants (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analysis_pass_grants_target ON public.analysis_pass_grants (target_user_id, created_at DESC);

COMMENT ON TABLE public.analysis_pass_grants IS
  'Append-only record of manual (no-payment) Analysis Pass grants made by admins via admin_issue_analysis_passes().';

ALTER TABLE public.analysis_pass_grants ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.analysis_pass_grants FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.analysis_pass_grants TO authenticated;
GRANT ALL ON public.analysis_pass_grants TO service_role;

CREATE POLICY "Admins can read Analysis Pass grants"
  ON public.analysis_pass_grants FOR SELECT TO authenticated
  USING (public.has_role((SELECT auth.uid()), 'admin'));

-- Look up the account behind an email, with its current pass balance, before issuing.
CREATE OR REPLACE FUNCTION public.admin_lookup_analysis_pass_account(p_email text)
RETURNS TABLE (user_id uuid, email text, full_name text, subscription_status text, pass_balance int)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_uid uuid;
BEGIN
  IF NOT public.has_role((SELECT auth.uid()), 'admin') THEN
    RAISE EXCEPTION 'Not authorised';
  END IF;
  IF v_email = '' THEN
    RAISE EXCEPTION 'Enter an email address';
  END IF;

  SELECT u.id INTO v_uid FROM auth.users u WHERE lower(u.email) = v_email LIMIT 1;
  IF v_uid IS NULL THEN
    RETURN; -- no row: the UI says "no account found"
  END IF;

  RETURN QUERY
  SELECT v_uid, v_email, p.full_name, p.subscription_status, public.available_ai_credits(v_uid)
    FROM (SELECT 1) one
    LEFT JOIN public.profiles p ON p.user_id = v_uid;
END;
$$;
REVOKE ALL ON FUNCTION public.admin_lookup_analysis_pass_account(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_lookup_analysis_pass_account(text) TO authenticated;

-- Issue passes. p_request_id is generated by the form once per attempt: a double click,
-- a retry or a replayed request returns the original grant (already_issued = true)
-- instead of issuing twice.
CREATE OR REPLACE FUNCTION public.admin_issue_analysis_passes(
  p_email text,
  p_credits int,
  p_note text,
  p_request_id uuid
)
RETURNS TABLE (user_id uuid, email text, credits_issued int, pass_balance int, already_issued boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_admin uuid := (SELECT auth.uid());
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_uid uuid;
  v_tx uuid;
  v_existing public.analysis_pass_grants%ROWTYPE;
BEGIN
  IF NOT public.has_role(v_admin, 'admin') THEN
    RAISE EXCEPTION 'Not authorised';
  END IF;
  IF p_request_id IS NULL THEN
    RAISE EXCEPTION 'A request id is required';
  END IF;
  IF p_credits IS NULL OR p_credits < 1 OR p_credits > 25 THEN
    RAISE EXCEPTION 'Issue between 1 and 25 passes at a time';
  END IF;
  IF p_note IS NULL OR btrim(p_note) = '' OR char_length(btrim(p_note)) > 200 THEN
    RAISE EXCEPTION 'A note (max 200 characters) is required';
  END IF;

  -- Replay of the same attempt: report the original grant, change nothing.
  SELECT g.* INTO v_existing FROM public.analysis_pass_grants g WHERE g.request_id = p_request_id;
  IF FOUND THEN
    RETURN QUERY SELECT v_existing.target_user_id, v_existing.target_email, v_existing.credits,
                        public.available_ai_credits(v_existing.target_user_id), true;
    RETURN;
  END IF;

  SELECT u.id INTO v_uid FROM auth.users u WHERE lower(u.email) = v_email LIMIT 1;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'No account found for that email address';
  END IF;

  -- Same ledger as a purchase. reason 'admin_grant' is distinguishable from 'consume:*' / 'refund:*' / purchases.
  INSERT INTO public.ai_credit_transactions (user_id, delta, reason)
  VALUES (v_uid, p_credits, 'admin_grant')
  RETURNING id INTO v_tx;

  INSERT INTO public.analysis_pass_grants (admin_user_id, target_user_id, target_email, credits, note, transaction_id, request_id)
  VALUES (v_admin, v_uid, v_email, p_credits, btrim(p_note), v_tx, p_request_id);

  RETURN QUERY SELECT v_uid, v_email, p_credits, public.available_ai_credits(v_uid), false;
END;
$$;
REVOKE ALL ON FUNCTION public.admin_issue_analysis_passes(text, int, text, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_issue_analysis_passes(text, int, text, uuid) TO authenticated;
